Repository Jimineei/Team1, pull requests merged in 2024-10, with the labels that each got.

#2 제품등록 기능 구현 완료
  teamproject/pom.xml
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/spring/root-context.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert_test.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/web.xml
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/src/main/webapp/resources/inc/header.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
  teamproject/src/main/webapp/uploads/084e6ca1-7dfd-4613-9cdb-e8d870dba1d5_galaxy1.jpg
  teamproject/src/main/webapp/uploads/183919f4-35eb-4e42-8f57-548ae5b40b90_galaxy3.jpg
  teamproject/src/main/webapp/uploads/43fcacf4-11a3-4cf6-8363-4b2650cce4da_galaxy2.jpg
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/MemberDAOImpl.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/persistence/ReceivingDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/MemberServiceImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/service/ReceivingServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/com/itwillbs/web/RcvController.class
  teamproject/target/classes/mappers/prodMapper.xml
  teamproject/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
  teamproject/target/m2e-wtp/web-resources/META-INF/maven/com.itwillbs/web/pom.properties
  teamproject/target/m2e-wtp/web-resources/META-INF/maven/com.itwillbs/web/pom.xml
  teamproject/target/test-classes/com/itwillbs/web/DataSourceTest.class
  teamproject/target/test-classes/com/itwillbs/web/MeberDAOTest.class
  teamproject/target/test-classes/com/itwillbs/web/MybatisTest.class
  teamproject/target/test-classes/com/itwillbs/web/MysqlConnectTest.class
Labels: 기능구현

#8 제품 목록 기능 구현
  teamproject/.classpath
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
Labels: 기능구현

#13 제품 목록 조회 일부 진행
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/uploads/084e6ca1-7dfd-4613-9cdb-e8d870dba1d5_galaxy1.jpg
  teamproject/src/main/webapp/uploads/43fcacf4-11a3-4cf6-8363-4b2650cce4da_galaxy2.jpg
  teamproject/src/main/webapp/uploads/4c47c308-c444-498b-90b3-29b1936ab898_galaxy4.jpg
  teamproject/src/main/webapp/uploads/9d5740ae-7893-4609-b9b6-772274df12f0_galaxy3.jpg
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
Labels: 기능구현

#18 제품 조회 기능 일부 구현 - 모달 화면구성과 이미지 작업 남아있음
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 기능구현

#21 제품조회 모달,이미지 이후에 작업하고 제품수정기능 우선 구현하기로 함
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 기능구현

#25 16 박재영 합류
  teamproject/src/main/java/com/itwillbs/domain/OrdersVO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/service/OrdersService.java
  teamproject/src/main/java/com/itwillbs/service/OrdersServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list-info.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/target/classes/mappers/orderMapper.xml
Labels: good first issue

#27 모달창에서 발주 수정 기능 구현, 발주 삭제 기능 구현
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/OrdersService.java
  teamproject/src/main/java/com/itwillbs/service/OrdersServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/target/classes/mappers/orderMapper.xml
Labels: good first issue

#28 재고테이블 추가후 컬럼제거, 제품목록까지 완료, 제품조회부터 재시작
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 기능구현

#31 제품조회 기능, 제품수정 기능 구현 완료
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert_test.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 기능구현

#33 제품 삭제 기능 구현 완료
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/uploads/4c47c308-c444-498b-90b3-29b1936ab898_galaxy4.jpg
  teamproject/src/main/webapp/uploads/9d5740ae-7893-4609-b9b6-772274df12f0_galaxy3.jpg
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 기능구현

#35 재고 이동 기능 세팅
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/uploads/fourLeafClover.jpg
  teamproject/target/classes/com/itwillbs/web/ProdController.class
Labels: 기능구현

#40 수정페이지에서 이미지 제거 기능, 재고이동 기능 일부 구현
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 기능구현

#41 발주 상태별 기능 추가 완료
  teamproject/src/main/java/com/itwillbs/domain/OrdersVO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/OrdersService.java
  teamproject/src/main/java/com/itwillbs/service/OrdersServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/target/classes/mappers/orderMapper.xml
Labels: good first issue

#55 화면 배치관련하여 css 변경중
  teamproject/src/main/java/com/itwillbs/domain/OrdersVO.java
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#56 재고이동기능 뷰페이지 값처리 완료 Service 작성 준비
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mybatis-config.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mybatis-config.xml
Labels: 기능구현

#57 공지사항 리스트
  teamproject/src/main/java/com/itwillbs/domain/NoticeVO.java
  teamproject/src/main/java/com/itwillbs/persistence/NoticeDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/NoticeDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/NoticeService.java
  teamproject/src/main/java/com/itwillbs/service/NoticeServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/NoticeController.java
  teamproject/src/main/resources/mappers/noticeMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/noticeEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeList.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeView.jsp
  teamproject/target/classes/mappers/noticeMapper.xml
Labels: good first issue

#60 재고 이동 기능 - Service, DAO, Mapper 작성 완료, 뷰페이지 작업 준비
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/target/classes/com/itwillbs/domain/MemberVO.class
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/MemberDAOImpl.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/MemberServiceImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 기능구현

#65 63 재고기능 구현 뷰페이지 수정 및 추가
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert_test.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/resources/css/kaiadmin.min.css
  teamproject/src/main/webapp/resources/inc/header.jsp
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 기능구현

#66 작업 진행중
  teamproject/src/main/java/com/itwillbs/domain/OrdersVO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/OrdersService.java
  teamproject/src/main/java/com/itwillbs/service/OrdersServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/target/classes/mappers/orderMapper.xml
Labels: good first issue

#70 root-context hikariConfig 서버db주소로 수정
  teamproject/src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 테스트

#72 63 재고기능 구현 뷰페이지 수정 및 추가
  teamproject/.classpath
  teamproject/.gitignore
  teamproject/.settings/org.eclipse.wst.common.component
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert_test.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/resources/css/kaiadmin.min.css
  teamproject/src/main/webapp/resources/inc/header.jsp
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/mappers/prodMapper.xml
Labels: 테스트

#78 바코드 생성 기능 구현 완료
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/target/classes/com/itwillbs/web/ProdController.class
Labels: 기능구현

#79 77 insert 페이지 최종 완료, 디자인은 위치 제외 완료, mapper 최종 완료, 페이징 기능, 검색 기능
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#86 제품관리 css 작업 완료
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/stockalert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
Labels: enhancement

#88 발주 목록 정리 완료, 디자인 완료, 시간 밀리초 수정 완료
  teamproject/src/main/java/com/itwillbs/domain/OrdersVO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/OrdersService.java
  teamproject/src/main/java/com/itwillbs/service/OrdersServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#90 테이블 수정 및 알림기능 수정
  teamproject/src/main/webapp/WEB-INF/views/prod/stockalert.jsp
Labels: enhancement

#98 메인페이지 일부 작업
  teamproject/src/main/java/com/itwillbs/web/MainController.java
  teamproject/src/main/webapp/WEB-INF/views/login.jsp
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: good first issue

#100 메인페이지 사이드바 작업중
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: good first issue

#105 메인페이지 사이드바 작업 완료 (/prod/insert.jsp 파일 참조)
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: good first issue

#108 리스트 수정중
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#110 사이드바 메뉴유지 기능로직 작성 완료
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
Labels: enhancement

#114 사이드바 메뉴 클릭 이벤트 작업 완료 정리 필요
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: 기능구현

#116 버그 원인 발견 검색 -> 삭제요청
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: bug

#124 거래처 완료 ---카카오맵 지도 api 완료
  teamproject/src/main/java/com/itwillbs/domain/CompanyVO.java
  teamproject/src/main/java/com/itwillbs/domain/WarehouseVO.java
  teamproject/src/main/java/com/itwillbs/persistence/CompanyDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/CompanyDAOImpl.java
  teamproject/src/main/java/com/itwillbs/persistence/WarehouseDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/WarehouseDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/CompanyService.java
  teamproject/src/main/java/com/itwillbs/service/CompanyServiceImpl.java
  teamproject/src/main/java/com/itwillbs/service/WarehouseService.java
  teamproject/src/main/java/com/itwillbs/service/WarehouseServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/AdminController.java
  teamproject/src/main/java/com/itwillbs/web/CompanyController.java
  teamproject/src/main/java/com/itwillbs/web/WarehouseController.java
  teamproject/src/main/resources/mappers/WarehouseMapper.xml
  teamproject/src/main/resources/mappers/companyMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/companyEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyList.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyView.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseList.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseMap.jsp
Labels: good first issue

#125 버그 확인 삭제 완료
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#128 메인페이지 차트작업 일부 진행 완료
  teamproject/src/main/java/com/itwillbs/domain/MainVO.java
  teamproject/src/main/java/com/itwillbs/persistence/MainDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/MainDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/MainService.java
  teamproject/src/main/java/com/itwillbs/service/MainServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/MainController.java
  teamproject/src/main/resources/mappers/mainMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/target/classes/mappers/.gitignore
Labels: enhancement

#130 메인페이지 그래프, mapper 수정
  teamproject/src/main/resources/mappers/mainMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/target/classes/com/itwillbs/domain/ReceivingVO.class
  teamproject/target/classes/com/itwillbs/persistence/MemberDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ReceivingDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ReceivingDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/MemberService.class
  teamproject/target/classes/com/itwillbs/web/RcvController.class
  teamproject/target/classes/mappers/WarehouseMapper.xml
  teamproject/target/classes/mappers/companyMapper.xml
  teamproject/target/classes/mappers/receivingMapper.xml
Labels: enhancement

#132 target/ .gitignore 추가
  teamproject/.gitignore
Labels: bug

#137 135 target 폴더 내용 삭제 진행
  teamproject/.gitignore
  teamproject/target/classes/com/itwillbs/domain/ProdVO.class
  teamproject/target/classes/com/itwillbs/domain/ReceivingVO.class
  teamproject/target/classes/com/itwillbs/persistence/MemberDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ProdDAOImpl.class
  teamproject/target/classes/com/itwillbs/persistence/ReceivingDAO.class
  teamproject/target/classes/com/itwillbs/persistence/ReceivingDAOImpl.class
  teamproject/target/classes/com/itwillbs/service/MemberService.class
  teamproject/target/classes/com/itwillbs/service/ProdService.class
  teamproject/target/classes/com/itwillbs/service/ProdServiceImpl.class
  teamproject/target/classes/com/itwillbs/service/ReceivingService.class
  teamproject/target/classes/com/itwillbs/service/ReceivingServiceImpl.class
  teamproject/target/classes/com/itwillbs/web/HomeController.class
  teamproject/target/classes/com/itwillbs/web/ProdController.class
  teamproject/target/classes/com/itwillbs/web/RcvController.class
  teamproject/target/classes/log4j.xml
  teamproject/target/classes/log4jdbc.log4j2.properties
  teamproject/target/classes/logback.xml
  teamproject/target/classes/mappers/.gitignore
  teamproject/target/classes/mappers/WarehouseMapper.xml
  teamproject/target/classes/mappers/companyMapper.xml
  teamproject/target/classes/mappers/memberMapper.xml
  teamproject/target/classes/mappers/noticeMapper.xml
  teamproject/target/classes/mappers/orderMapper.xml
  teamproject/target/classes/mappers/prodMapper.xml
  teamproject/target/classes/mappers/receivingMapper.xml
  teamproject/target/classes/mappers/userMapper.xml
  teamproject/target/classes/mybatis-config.xml
  teamproject/target/m2e-wtp/web-resources/META-INF/.gitignore
  teamproject/target/m2e-wtp/web-resources/META-INF/maven/com.itwillbs/web/.gitignore
  teamproject/target/m2e-wtp/web-resources/META-INF/maven/com.itwillbs/web/pom.xml
  teamproject/target/test-classes/com/itwillbs/web/DataSourceTest.class
  teamproject/target/test-classes/com/itwillbs/web/MeberDAOTest.class
  teamproject/target/test-classes/com/itwillbs/web/MybatisTest.class
  teamproject/target/test-classes/com/itwillbs/web/MysqlConnectTest.class
  teamproject/target/test-classes/log4j.xml
Labels: bug

#141 로그인 아이디 받아오기, 발주요청시 alert창 확인 및 리스트로 이동
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#150 149 창고거래처공지사항 사이드바 작업 및 사용자 로그인시 항목 안보이게
  teamproject/src/main/webapp/WEB-INF/views/companyEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyList.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyView.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeList.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeView.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseList.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseView.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: good first issue

#152 메인페이지 채팅창 기능 구현중
  teamproject/pom.xml
  teamproject/src/main/java/com/itwillbs/chat/ChattingHandler.java
  teamproject/src/main/java/com/itwillbs/persistence/MainDAOImpl.java
  teamproject/src/main/java/com/itwillbs/web/MainController.java
  teamproject/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/web.xml
  teamproject/src/main/webapp/resources/inc/footer.jsp
Labels: 기능구현

#157 발주 목록페이지에서 발주자 id와 그 id에 대한 정보 미스매치 수정
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#163 모달 디자인 일부 수정
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#164 메인페이지 채팅 기능 구현 중
  teamproject/src/main/java/com/itwillbs/chat/ChattingHandler.java
  teamproject/src/main/resources/log4j.xml
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/stockalert.jsp
Labels: 기능구현

#172 거래처, 공지사항 검색기능 페이징처리완료-
  teamproject/src/main/webapp/WEB-INF/views/companyEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyList.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyView.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeList.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeView.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseList.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseMap.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseView.jsp
  teamproject/src/main/webapp/WEB-INF/views/warehouseProductList.jsp
Labels: good first issue

#177 169-제품조회-qr코드-이미지-구현
  teamproject/src/main/java/com/itwillbs/chat/ChattingHandler.java
  teamproject/src/main/java/com/itwillbs/web/MainController.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/resources/css/bootstrap.min.css
  teamproject/src/main/webapp/resources/img/kaiadmin/favicon.ico
  teamproject/src/main/webapp/resources/img/kaiadmin/favicon.png
  teamproject/src/main/webapp/resources/img/kaiadmin/favicon.svg
  teamproject/src/main/webapp/resources/img/kaiadmin/logo_dark.png
  teamproject/src/main/webapp/resources/img/kaiadmin/logo_dark.svg
  teamproject/src/main/webapp/resources/img/kaiadmin/logo_light.png
  teamproject/src/main/webapp/resources/img/kaiadmin/logo_light.svg
  teamproject/src/main/webapp/resources/inc/header.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: 기능구현

#180 사이드바, 제품관리 페이지 수정
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/stockalert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/resources/css/kaiadmin.min.css
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: enhancement

#184 메인페이지 수정
  teamproject/src/main/java/com/itwillbs/persistence/MainDAOImpl.java
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/stockalert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/resources/css/bootstrap.min.css
  teamproject/src/main/webapp/resources/css/css-table/leaderFont.css
  teamproject/src/main/webapp/resources/css/kaiadmin.min.css
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/src/main/webapp/resources/inc/header.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: 기능구현

#195 발주 완료된 정보 상세정보에서 버튼 클릭시 입고 요청 페이지로 이동 및 발주관리번호 보내기, 상대거래처에서 발주 수락, 거절 기능
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list02.jsp
Labels: good first issue

#201 상대 거래처의 발주 요청 페이지 구현 뷰페이지까지 완료, 목록에서 발주 상태별로 검색 기능 구현 완료
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/OrdersService.java
  teamproject/src/main/java/com/itwillbs/service/OrdersServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-insert02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#204 재고이동이력 페이지
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/movestock.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/stockmove.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
Labels: 기능구현

#206 재고이동이력 페이지 작업완료
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/movestock.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/stockalert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: 기능구현

#209 공지사항 게시글 상단고정 및 거래처 삭제 상태 변경
  teamproject/src/main/java/com/itwillbs/domain/CompanyVO.java
  teamproject/src/main/java/com/itwillbs/domain/NoticeVO.java
  teamproject/src/main/java/com/itwillbs/persistence/CompanyDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/CompanyDAOImpl.java
  teamproject/src/main/java/com/itwillbs/persistence/NoticeDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/NoticeDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/CompanyService.java
  teamproject/src/main/java/com/itwillbs/service/CompanyServiceImpl.java
  teamproject/src/main/java/com/itwillbs/service/NoticeService.java
  teamproject/src/main/java/com/itwillbs/service/NoticeServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/CompanyController.java
  teamproject/src/main/java/com/itwillbs/web/NoticeController.java
  teamproject/src/main/resources/mappers/companyMapper.xml
  teamproject/src/main/resources/mappers/noticeMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/companyEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyList.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeList.jsp
Labels: good first issue

#217 재고이동이력 기능 완료
  teamproject/src/main/java/com/itwillbs/domain/ProdVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/movestock.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/stockalert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
Labels: 기능구현

#220 거래처 발주 요청 페이지 수정, 거래처 발주 목록 페이지 구현임
  teamproject/src/main/java/com/itwillbs/domain/CordersVO.java
  teamproject/src/main/java/com/itwillbs/persistence/CordersDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/CordersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/CordersService.java
  teamproject/src/main/java/com/itwillbs/service/CordersServiceImpl.java
  teamproject/src/main/java/com/itwillbs/service/OrdersService.java
  teamproject/src/main/java/com/itwillbs/service/OrdersServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/CorderController.java
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/resources/mappers/corderMapper.xml
  teamproject/src/main/resources/mappers/orderMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/order-insert02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list03.jsp
Labels: good first issue

#223 디자인 제외 최종 수정 완료
  teamproject/src/main/java/com/itwillbs/web/CorderController.java
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-insert02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list03.jsp
Labels: good first issue

#226 제품관리-수정
  teamproject/src/main/java/com/itwillbs/web/MainController.java
  teamproject/src/main/java/com/itwillbs/web/ShpController.java
  teamproject/src/main/webapp/WEB-INF/views/cmain.jsp
  teamproject/src/main/webapp/WEB-INF/views/login.jsp
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/movestock.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/src/main/webapp/resources/inc/header.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: enhancement

#231 거래처, 공지사항, 창고 jsp 페이지들 전체 수정 + 창고지도 검색기능 추가
  teamproject/src/main/webapp/WEB-INF/views/companyEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyList.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyView.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeList.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeView.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseList.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseMap.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseView.jsp
  teamproject/src/main/webapp/WEB-INF/views/warehouseProductList.jsp
Labels: good first issue

#234 공지사항 오류 수정
  teamproject/src/main/webapp/WEB-INF/views/noticeEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeList.jsp
Labels: good first issue

#235 거래처 메인페이지
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdService.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/MainController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/cmain.jsp
  teamproject/src/main/webapp/resources/inc/companyFooter.jsp
  teamproject/src/main/webapp/resources/inc/companySidebar.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
Labels: enhancement

#239 사이드 바 제외 오류 수정 완료
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-insert02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list03.jsp
Labels: good first issue

#242 제목 및 페이지 헤더타이틀 수정
  teamproject/src/main/webapp/WEB-INF/views/cmain.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyList.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyView.jsp
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeList.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeView.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/list.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/movestock.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/stockalert.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseEdit.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseList.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseMap.jsp
  teamproject/src/main/webapp/WEB-INF/views/wareHouseView.jsp
  teamproject/src/main/webapp/WEB-INF/views/warehouseProductList.jsp
  teamproject/src/main/webapp/resources/css/css-table/leaderFont.css
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: enhancement

#244 버튼 css 제외 오류 수정 완료
  teamproject/src/main/java/com/itwillbs/domain/CordersVO.java
  teamproject/src/main/java/com/itwillbs/web/CorderController.java
  teamproject/src/main/webapp/WEB-INF/views/order-insert02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list03.jsp
  teamproject/src/main/webapp/resources/inc/companySidebar.jsp
Labels: good first issue

#246 버튼 css 수정완료
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list03.jsp
Labels: good first issue

#249 재고이동-검증로직-추가
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/ProdServiceImpl.java
  teamproject/src/main/java/com/itwillbs/web/ProdController.java
  teamproject/src/main/resources/mappers/prodMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/prod/movestock.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
Labels: bug

#254 header, footer padding 값 0, 거래처 페이지 사이드바 목록 이름 수정
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-insert02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list03.jsp
  teamproject/src/main/webapp/resources/inc/companySidebar.jsp
  teamproject/src/main/webapp/resources/inc/sidebar.jsp
Labels: good first issue

#258 css 수정 (버튼 색깔 통일)
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
Labels: good first issue

#261 System.print.out, console.log, logger.info 제거 및 변경 작업 완료
  teamproject/src/main/java/com/itwillbs/login/SNSLogin.java
  teamproject/src/main/java/com/itwillbs/persistence/MemberDAOImpl.java
  teamproject/src/main/java/com/itwillbs/persistence/OrdersDAOImpl.java
  teamproject/src/main/java/com/itwillbs/persistence/ReceivingDAOImpl.java
  teamproject/src/main/java/com/itwillbs/persistence/ShippingDAOImpl.java
  teamproject/src/main/java/com/itwillbs/persistence/UserDAOImpl.java
  teamproject/src/main/java/com/itwillbs/service/EmailService.java
  teamproject/src/main/java/com/itwillbs/web/EmailController.java
  teamproject/src/main/java/com/itwillbs/web/MemberController.java
  teamproject/src/main/java/com/itwillbs/web/NoticeController.java
  teamproject/src/main/java/com/itwillbs/web/OrderController.java
  teamproject/src/main/java/com/itwillbs/web/RcvController.java
  teamproject/src/main/java/com/itwillbs/web/ShpController.java
  teamproject/src/main/webapp/WEB-INF/views/admin/CompanyMemberList.jsp
  teamproject/src/main/webapp/WEB-INF/views/admin/MemberList.jsp
  teamproject/src/main/webapp/WEB-INF/views/companyView.jsp
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/noticeInsert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-insert.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list02.jsp
  teamproject/src/main/webapp/WEB-INF/views/order-list03.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/transfer.jsp
  teamproject/src/main/webapp/WEB-INF/views/rcvList2.jsp
  teamproject/src/main/webapp/WEB-INF/views/shpList2.jsp
  teamproject/src/main/webapp/WEB-INF/views/shpRQ.jsp
  teamproject/src/main/webapp/resources/inc/companyFooter.jsp
  teamproject/src/main/webapp/resources/inc/companyHeader.jsp
  teamproject/src/main/webapp/resources/inc/footer.jsp
  teamproject/src/main/webapp/resources/inc/header.jsp
  teamproject/src/main/webapp/resources/js/pwInquiry.js
  teamproject/src/main/webapp/resources/js/signUp.js
  teamproject/src/test/java/com/itwillbs/web/DataSourceTest.java
  teamproject/src/test/java/com/itwillbs/web/MeberDAOTest.java
  teamproject/src/test/java/com/itwillbs/web/MybatisTest.java
  teamproject/src/test/java/com/itwillbs/web/MysqlConnectTest.java
Labels: enhancement

#265 MainMapper, 재고이동 페이지 수정완료
  teamproject/src/main/java/com/itwillbs/domain/MainVO.java
  teamproject/src/main/java/com/itwillbs/persistence/ProdDAOImpl.java
  teamproject/src/main/resources/mappers/mainMapper.xml
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
  teamproject/src/main/webapp/WEB-INF/views/prod/movestock.jsp
Labels: bug, enhancement

#271 채팅기능 일부 수정
  teamproject/src/main/java/com/itwillbs/chat/ChattingHandler.java
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
Labels: bug

#282 콘솔아트
  teamproject/src/main/webapp/WEB-INF/views/main.jsp
Labels: enhancement
